(()=>{let running=false,run=0,panel,status;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const visible=e=>{if(!e)return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=="none"&&s.visibility!=="hidden};
function composer(){for(const s of ["#prompt-textarea","textarea[placeholder*='Message']","textarea[placeholder*='mensagem' i]","div[contenteditable='true'][role='textbox']","div[contenteditable='true']"]){const e=[...document.querySelectorAll(s)].find(visible);if(e)return e}return null}
function send(){const a=["button[data-testid='send-button']","button[aria-label='Send prompt']","button[aria-label='Enviar']","button[aria-label*='Send' i]","button[aria-label*='Enviar' i]"];for(const s of a){const e=[...document.querySelectorAll(s)].find(e=>visible(e)&&!e.disabled);if(e)return e}return null}
function stopBtn(){return [...document.querySelectorAll("button")].find(e=>visible(e)&&((e.getAttribute("aria-label")||"")+" "+(e.getAttribute("title")||"")).toLowerCase().match(/stop|parar/))}
function put(e,t){e.focus();if(e instanceof HTMLTextAreaElement){const p=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value").set;p.call(e,t);e.dispatchEvent(new Event("input",{bubbles:true}));return}if(e.isContentEditable){e.textContent="";e.appendChild(document.createTextNode(t));e.dispatchEvent(new InputEvent("input",{bubbles:true,inputType:"insertText",data:t}))}}
function ui(){if(panel)return;panel=document.createElement("div");panel.id="gpt-auto-panel";panel.innerHTML='<span id="gpt-auto-dot"></span><span id="gpt-auto-status"></span><button id="gpt-auto-stop">Parar</button>';document.body.appendChild(panel);status=panel.querySelector("#gpt-auto-status");panel.querySelector("#gpt-auto-stop").onclick=halt}
function show(v){ui();panel.style.display=v?"flex":"none"}function stat(t){ui();status.textContent=t}
async function waitComposer(id){for(let i=0;i<120&&running&&id===run;i++){const e=composer();if(e)return e;await sleep(250)}throw Error("Campo de mensagem não encontrado")}
async function waitDone(id){await sleep(600);let saw=false,stable=0,last="";for(let i=0;i<300&&running&&id===run;i++){const s=stopBtn(),b=send();if(s){saw=true;stable=0}else if(saw){const x=(document.querySelector("main")||document.body).innerText.slice(-1200);if(x===last)stable++;else{last=x;stable=0}if(b&&stable>=2)return}else if(b&&!b.disabled){await sleep(1200);if(!stopBtn())return}await sleep(400)}}
async function one(text,id){const e=await waitComposer(id);put(e,text);await sleep(150);const b=send();if(b)b.click();else e.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",code:"Enter",keyCode:13,which:13,bubbles:true}));await waitDone(id)}
async function start(o){halt();if(!o.message?.trim())return{ok:false,error:"Digite uma mensagem."};running=true;run++;const id=run;show(true);let n=0;while(running&&id===run&&(o.infinite||n<o.repeats)){n++;stat(`Enviando ${n}/${o.infinite?"∞":o.repeats}`);try{await one(o.message,id)}catch(e){stat("Erro: "+e.message);running=false;break}if(running&&(o.infinite||n<o.repeats)&&o.delay>0)await sleep(o.delay*1000)}if(id===run){running=false;stat(`Concluído: ${n} envio(s)`);setTimeout(()=>show(false),2500)}return{ok:true}}
function halt(){running=false;run++;if(panel){stat("Parado.");setTimeout(()=>show(false),700)}}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m.action==="PING"){reply({ok:true});return}if(m.action==="START"){start(m).then(reply);return true}if(m.action==="STOP"){halt();reply({ok:true})}});
})();